spring:
  application:
    name: gateway-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  prefix: /api
  ignored-services: '*'